[package]
name = "lpg"
version = "0.2.0"
authors = ["femboy.tv", "Atakku", "Loïc Mathieu"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.25.5"
